version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    user: "node"

    # Use "forwardPonoderts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "8001:27017"
  auth:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - user-data:/data/db
    ports:
      - "8002:3306"
      

    # Uncomment to change startup options
    environment:
     MONGO_INITDB_ROOT_USERNAME: tbrooks
     MONGO_INITDB_ROOT_PASSWORD: Qu33nL@dy
     MONGO_INITDB_DATABASE: blog-repo
     MYSQL_ROOT_PASSWORD: Qu33nL@dy
     MYSQL_DATABASE_URL: mysql://root:Qu33nL@dy@localhost:8802/DATABASE
     MONGO_DATABASE_URL: mongodb://admin-root:minion_flacon@localhost:8001


    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mongodb-data:
  user-data:q