version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    user: "node"
    env_file:
      - ./../.devcontainer.env

    # Use "forwardPonoderts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "8001:27017"
    environment:
     MONGO_INITDB_ROOT_USERNAME: writer
     MONGO_INITDB_ROOT_PASSWORD: Qu33n_L@DY
     MONGO_INITDB_DATABASE: blogs

  auth:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - user-auth-data:/data/db
    ports:
      - "8002:27017"
      

    environment:
     MONGO_INITDB_ROOT_USERNAME: auth
     MONGO_INITDB_ROOT_PASSWORD: L0rd_$UN
     MONGO_INITDB_DATABASE: credentials 

    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mongodb-data:
  user-auth-data: